// Valeurs par défaut de chaque page — miroir des DEFAULTS dans chaque composant
// Utilisé par le CMS admin pour pré-remplir les champs vides
export const PAGE_DEFAULTS: Record<string, Record<string, string>> = {
  home: {
    hero_badge:           'Monica Schneider · Executive Coach · Happy Humans',
    hero_title:           "Clarté, confiance et relations qui vous ressemblent",
    hero_subtitle:        "Executive Coach certifiée AoEC · EMCC Practitioner · Philosophical Counselling",
    hero_cta_primary:     "Séance découverte gratuite",
    hero_cta_contact:     "Me contacter",
    services_badge:       'Accompagnement',
    services_title:       'Comment puis-je vous aider ?',
    services_intro:       'Que vous soyez un particulier en quête de clarté ou une organisation qui veut remettre de l&apos;alignement dans ses équipes.',
    services_b2c_title:   'Pour les particuliers',
    services_b2c_text:    "Managers, dirigeants, entrepreneurs ou personnes en transition qui veulent retrouver de la clarté, de la confiance et une direction qui leur ressemble vraiment.",
    services_b2c_cta:     'Réserver une séance découverte →',
    services_b2b_title:   'Pour les organisations',
    services_b2b_text:    "Coaching de leadership, ateliers, séminaires et accompagnement du changement pour remettre de l'alignement et de l'élan dans les équipes.",
    services_b2b_cta:     "Discuter d'un projet →",
    cards_section_badge:  'Aller plus loin',
    cards_section_title: 'Explorez les thématiques',
    cards_link_label:    'Découvrir →',
    booking_badge:        'Agenda',
    booking_modal_title: 'Choisissez votre créneau',
    booking_modal_subtitle: 'Séance découverte offerte · 45 minutes · Sans engagement',
    contact_section_badge: 'Contact',
    contact_section_title: 'Une question ? Écrivez-moi',
    contact_section_subtitle: 'Réponse sous 48h.',
    form_success_title:  'Message envoyé !',
    form_success_body:   'Monica vous répondra sous 48h à {email}.',
    form_sending:        'Envoi en cours…',
    form_submit:         'Envoyer le message',
    contact_email:       'happyhumans.coaching@gmail.com',
  // home_card_order_* are defined in app/page.tsx DEFAULTS
  },
  'a-propos': {
    hero_image:       '',
    hero_badge:       'À propos',
    page_title:       'Leadership coaching en profondeur',
    intro_text:       "Une pratique née au croisement de l'entreprise, du branding, de la transformation humaine et de la pratique philosophique.",
    bio_badge:        'Mon histoire',
    bio_title:        'Deviens qui tu es',
    bio_text:         "Les 10 premières années de ma carrière ont été dédiées au marketing international : développement de produits, de marques, d'histoires et d'expériences inoubliables, en Allemagne, en France, au Royaume-Uni et en Europe de l'Est pour Henkel, LVMH et L'Oréal.\n\nEn 2020, j'ai mis fin à l'aventure L'Oréal et j'ai exploré de nouvelles vies.\n\nJe me suis formée à l'Executive Coaching. Une des choses qui m'avait le plus animée a été le développement des individus et des équipes. À travers cette formation et le début de ma pratique, j'ai découvert que ce métier était fait pour moi.\n\nDans le coaching, j'arrivais à créer un espace où mes clients trouvent le courage de se confronter à leurs limites, à leurs doutes et à leurs vulnérabilités pour réaliser une transformation libératrice qui les rapproche de qui ils sont, de leur puissance et de leur sourire le plus confiant.\n\nÊtre témoin et guide dans cette démarche est un honneur qui m'anime plus que tout.\n\nPour enrichir mon approche et retrouver un de mes amours de jeunesse, j'ai également entrepris un Master de Pratique Philosophique. J'ai fait mon mémoire sur le bonheur.\n\nDeux grandes conclusions :\n1. Ce n'est pas le bonheur qui fait la différence, mais comment on réagit dans l'adversité — quand la vie ne va pas comme on veut.\n2. Une discipline ne suffit pas. Il faut comprendre son cerveau (neurosciences), savoir créer son bonheur (psychologie positive), repérer quand son inconscient reprend le dessus (psychologie classique), entraîner le cerveau à réduire le cortisol (méditation) et challenger ses pensées (pratique philosophique).\n\nJe me suis construit une boîte à outils que j'ai appliquée à ma propre vie au cours des 6 dernières années — Happiness Design. Je l'ai aussi intégrée dans mes coachings, et cela a fait la différence pour mes clients.\n\nAujourd'hui je continue à accompagner des individus ou des entreprises aux moments clés des carrières (promotion et prise de poste, transitions, reconversion), pour booster le sens et l'engagement (conseil en communication interne, team coaching) et même pendant les moments clés du reste de la vie (mariage, séparation, parentalité, deuil, retraite, fin de vie).\n\nMa conviction, ligne directrice dans toutes mes interventions, est simple. Pour chaque nouvelle étape, nous devons entreprendre une transformation en tant qu'individu ou en tant qu'équipe. Je suis à vos côtés avec ma boîte à outils multidisciplinaire pour coller au mieux à votre chemin unique.\n\nJe souhaite aussi rendre cette boîte à outils du bonheur, même dans une vie chaotique, accessible au plus grand nombre. Ce projet s'appelle Happiness Design.",
    photo:            '',
    coaching_label:   'Coaching',
    coaching_text1:  "Le coaching est une danse entre le coach et le coaché. À travers les questions du coach, le coaché réfléchit, change de perspective, fait l'expérience de révélations. Il ou elle trouve en soi les meilleures solutions pour avancer sereinement vers son objectif.",
    coaching_text2:  "À noter : ma pratique de coaching est enrichie, quand la situation s'y prête, par de la philosophie pratique.",
    coaching_cta:    'Voir le coaching →',
    mentoring_label: 'Mentoring',
    mentoring_text:  "Je vous offre mes conseils sur une problématique alignée avec mon expertise : comment être visible tout en restant authentique, comment démontrer du leadership, quel plan de communication interne mettre en place, comment naviguer les différences culturelles.",
    mentoring_cta:   'Me contacter →',
    acc_badge:       'Accompagnement',
    acc_title:       'Mes coachings et mentorings',
    acc_subtitle:    '2 approches complémentaires',
    hd_badge:        'Happiness Design',
    hd_text:         "Je souhaite rendre cette boîte à outils du bonheur, même dans une vie chaotique, accessible au plus grand nombre. Ce projet s'appelle Happiness Design.",
    hd_cta:          "Pour en savoir plus, c'est par ici →",
    footer_cta_title: "Envie d'en savoir plus ?",
    footer_cta_coaching: 'Voir le coaching',
    footer_cta_booking:  'Réserver une séance (45 min)',
  },
  booking: {
    hero_badge:         'Réservation',
    hero_title:         'Réserver une séance',
    hero_subtitle:      'Séance découverte offerte · 45 min · Sans engagement',
    reassurance_1_title: 'Séance découverte gratuite',
    reassurance_1_desc:  '45 minutes sans engagement pour vous présenter et voir si le coaching vous correspond.',
    reassurance_2_title: 'Confirmation immédiate',
    reassurance_2_desc:  'La réservation est confirmée instantanément dans votre agenda Google ou Outlook.',
    reassurance_3_title: 'Annulation libre',
    reassurance_3_desc:  "Vous pouvez reporter ou annuler jusqu'à 24h avant la séance, sans frais.",
    footer_note:         'Toutes les séances se déroulent en ligne (Google Meet) ou en présentiel à Paris, selon votre préférence.',
    email_booking_text:  'Écrire à Monica →',
  },
  coaching: {
    hero_image:         '',
    hero_badge:         'Coaching',
    hero_title:         "Il y a des moments où il faut réapprendre à habiter son rôle.",
    hero_subtitle:      "Executive Coach certifiée AoEC · EMCC Practitioner · Monica Schneider accompagne des managers, dirigeants et personnes en transition qui veulent retrouver clarté, confiance et une direction qui leur ressemble vraiment.",
    hero_cta_primary:   'Séance découverte gratuite (45 min)',
    hero_cta_contact:   'Me contacter',
    coaching_b2c_image: '',
    coaching_b2c_badge: 'Individuel',
    coaching_b2c_title: 'Coaching individuel',
    coaching_b2c_text:  "Un espace pour ralentir, regarder ce qui se passe vraiment — et construire un mouvement qui tient dans la durée.\n\nLe coaching que je propose n'est pas un conseil. C'est un accompagnement qui part de là où vous êtes vraiment.\n\nJe m'appuie sur des techniques classiques d'executive coaching (modèles GROW, Gestalt, Solutions Focused, Co-active…) mais aussi sur des outils rencontrés plus rarement — méditation, philosophie, psychologie, design thinking — pour travailler sur la transformation que vous devez accomplir au plus profond de vous pour réaliser vos objectifs.\n\nPour offrir du recul, de la clarté et de nouvelles perspectives. Vous y voyez plus clair, y compris sur les prochaines actions à mettre en place.\n\nVous vous retrouvez — et vous êtes prêt·e à accélérer avec un élan et une clarté revigorants.",
    coaching_b2c_cta_link: 'Me contacter →',
    coaching_b2b_image: '',
    coaching_b2b_badge: 'Organisations',
    coaching_b2b_title: 'Pour les organisations',
    coaching_b2b_text:  "Coaching de dirigeants, ateliers de cohésion, accompagnement du changement et séminaires sur mesure.\n\nQuand une équipe perd de sa cohérence, les résultats s'en ressentent toujours. Je travaille avec les dirigeants et les organisations pour remettre de l'alignement — entre les personnes, entre les objectifs et les moyens, entre ce qu'on dit et ce qu'on fait.",
    coaching_b2b_cta_link: 'Découvrir →',
    programs_badge:     'Tarifs',
    programs_title:     'Programmes & investissement',
    program_discovery_price:  'Gratuit',
    program_discovery_unit:    '45 min',
    program_single_price:      '120 €',
    program_single_unit:       '60 min',
    program_poste_price:       'Sur devis',
    program_poste_unit:        '',
    program_hd_label:   'Happiness Design',
    program_hd_unit:    '12 séances individuelles',
    program_hd_desc:    '12 séances pour reprendre les rênes de votre vie et de votre bonheur — au boulot et ailleurs.',
    program_hd_cta:    'En savoir plus',
    tunnel_title:              'Prête à commencer ?',
    tunnel_cta_primary:        'Réserver maintenant →',
    tunnel_cta_secondary:       'Poser une question',
    tunnel_reassurance:        'Séance découverte gratuite · 45 min · Sans engagement · Confirmation immédiate',
    testimonials_badge:     'Témoignages',
    testimonials_title:     "Ce qu'ils en disent",
    testimonials_footnote: "* Prénom modifié",
    cta_title:         'Prêt·e à commencer ?',
    form_cta_title:    "Commençons par une séance découverte de 45 min — gratuite et sans engagement.",
    form_cta_button:   'Séance découverte gratuite (45 min)',
    form_intro:         'Décrivez votre enjeu ou posez une question — je vous répondrai sous 48h.',
    reassurance:        '100% confidentiel · Sans engagement · Réponse sous 48h · Séance découverte offerte',
    program_1_label: 'Séance découverte',
    program_1_desc:  'Premier échange pour clarifier votre situation, vos attentes et voir si le coaching vous convient.',
    program_1_price: 'Gratuit',
    program_1_unit:  '45 min',
    program_1_cta:   'Réserver une séance découverte',
    program_2_label: 'Séance individuelle',
    program_2_desc:  'Séance ponctuelle pour travailler sur un sujet précis ou maintenir une dynamique engagée.',
    program_2_price: '120 €',
    program_2_unit:  '60 min',
    program_2_cta:   'Réserver une séance',
    program_3_label: 'Programme prise de poste',
    program_3_desc:  'Structurer ses 90 premiers jours, asseoir son leadership et incarner pleinement son nouveau rôle — avec clarté et confiance.',
    program_3_format: '6 séances + 1 point hebdo de 30 min pendant les 90 premiers jours',
    program_3_price: 'Sur devis',
    program_3_cta:   'Réserver une séance découverte',
    testimonial_1_quote:  "J'étais le bon élève typique : attendre d'avoir tout compris et tout structurer avant d'agir, ce qui me freinait clairement dans mon rôle. Grâce à mes échanges avec Monica, j'ai compris mes mécanismes limitants et découvert de nouvelles perspectives. Le déclic du « cancre intelligent » m'a permis de voir mes forces autrement : j'ose proposer, tester, décider plus vite. Résultat : plus d'impact, plus de visibilité, et des résultats business concrets.",
    testimonial_1_name:   "Thibault*",
    testimonial_1_title:  "Directeur Marketing, Tech",
    testimonial_2_quote:  "I highly recommend the coaching sessions that Monica Schneider offers. My experience with her has been greatly satisfactory and has allowed me to achieve goals and mindsets that would have been very difficult to accomplish otherwise. She has a vast knowledge of the questioning technique and made every session worth and developmental. Monica's coaching style reflects her professionalism and her engaging nature that has allowed me to express myself openly. She provided a psychological safe environment.",
    testimonial_2_name:   "Maria*",
    testimonial_2_title:  "Learning & Development Director, Banking",
    testimonial_3_quote:  "I want to thank Monica for her inspiring, relieving, insightful and energizing sessions! She opened up valuable new perspectives on my current situation and helped me get to know myself better. It is amazing, but just in a few sessions I was able to view my situation from a completely new angle, and suddenly see the road to my new self.",
    testimonial_3_name:   "David*",
    testimonial_3_title:  "Governmental Think Tank",
  },
  'sparring-partner': {
    hero_badge:         'Sparring Partner',
    hero_title:         "Un regard extérieur stratégique par une pair qui comprend vos enjeux",
    hero_desc:          "Ex-L'Oreal, ex-LVMH, 5 langues, philo-coaching. Monica vous offre le recul qu'un manager ne peut pas toujours trouver en interne.",
    hero_cta_primary:   'Réserver une session',
    hero_cta_secondary: 'Poser une question',
    section_badge:      "Pour quoi faire ?",
    section_title:      'Les situations qui appellent un sparring partner',
    use_case_1_title:  'Préparer un pitch',
    use_case_1_desc:   'Monica joue le contre-argument, affûte vos arguments et renforce votre posture.',
    use_case_2_title:  'Challenger une stratégie',
    use_case_2_desc:   "Un regard extérieur de quelqu'un qui connaît vos enjeux métier.",
    use_case_3_title:  'Prise de poste',
    use_case_3_desc:   'Nouvelle équipe, nouvelles attentes. Prendre de la hauteur rapidement.',
    use_case_4_title:  'Communication multiculturelle',
    use_case_4_desc:   '5 pays, 5 langues. Les codes implicites qui font ou défont une relation.',
    use_case_5_title:  'Décision difficile',
    use_case_5_desc:   'Partir ? Rester ? Négocier ? Un interlocuteur de confiance pour y voir clair.',
    why_section_badge: 'Pourquoi Monica ?',
    why_section_title: "Ex-L'Oreal, ex-LVMH, philo-coach et Happiness Design",
    experience_items:   "10 ans marketing — Henkel, LVMH, L'Oréal\nExecutive Coach certifiée AoEC & EMCC\nMaster en Philosophical Counselling\n5 langues : FR, EN, RO, DE, ES\nMéthode Happiness Design\n5 pays, 12 villes",
    cta_title:          'Prêt à challenger vos idées ?',
    cta_desc:           'Session 60 à 90 min. Conversation découverte de 30 min offerte.',
    cta_primary:       'Réserver une session',
    cta_secondary:     'Poser une question',
    sparring_price:    'Sur devis',
  },
  relations: {
    hero_badge:          'Relations & Attachement',
    hero_title:          'Quel est votre style d\'attachement ?',
    hero_description:    'Un outil de découverte douce pour mieux comprendre comment vous vous connectez aux autres.',
    hero_cta_primary:    'Séance découverte gratuite',
    hero_cta_secondary:  'Faire le test d\'attachement',
    quiz_badge:          'Quiz · Découvrez votre profil',
    styles_badge:        'Théorie de l\'attachement',
    styles_title:        'Les 4 styles d\'attachement',
    styles_subtitle:     'Notre façon d\'entrer en relation à l\'âge adulte reflète des modèles construits dès la petite enfance. Quel est le vôtre ?',
    manifestations_badge:   'Dynamique relationnelle',
    manifestations_title:    'La danse Anxieux–Évitant',
    manifestations_subtitle: 'Le couple le plus fréquent… et le plus volatile. Comprendre ce mécanisme change tout.',
    manifestations_anxious_avoidant_text: 'Le couple le plus fréquent… et le plus volatile. Comprendre ce mécanisme change tout.',
    manifestations_anxious_title:   'Le profil Anxieux',
    manifestations_anxious_desc:     'Par peur de perdre le lien, il poursuit et demande plus d\'attention (hyperactivation). Plus il ressent de distance, plus il accélère.',
    manifestations_avoidant_title:  'Le profil Évitant',
    manifestations_avoidant_desc:   'Craint la dépendance, alors il fuit et se distance (désactivation). Plus l\'anxieux s\'approche, plus il s\'éloigne.',
    manifestations_goodnews_text:    'Bonne nouvelle : ces réactions ne relèvent pas d\'un manque d\'amour, mais d\'un système biologique d\'attachement activé. Les comprendre permet de sortir du piège et de retrouver la connexion.',
    healing_badge:       'Neuroplasticité & guérison',
    healing_title:        'L\'attachement sécurisé acquis',
    healing_subtitle:     'Votre style d\'attachement n\'est pas une fatalité. Grâce à la neuroplasticité du cerveau, il est possible de le transformer.',
    healing_step1_title:  'La conscience de soi',
    healing_step1_desc:   'Observer ses réactions sans se juger. Identifier ses déclencheurs émotionnels. Créer un espace entre le stimulus et la réponse.',
    healing_step2_title: 'Les relations correctrices',
    healing_step2_desc:   'S\'entourer de personnes sécures et fiables. Leur présence apaisante va progressivement « recâbler » le système nerveux vers plus de sécurité.',
    healing_step3_title: 'La thérapie (EFT)',
    healing_step3_desc:   'La Thérapie Centrée sur les Émotions (Sue Johnson) utilise la relation thérapeutique comme base de sécurité pour transformer les modèles internes.',
    comm_badge:     'Outils pratiques',
    comm_title:     'Communiquer efficacement',
    comm_subtitle:  'Formuler ses besoins selon son style d\'attachement : 3 règles pour apaiser les tensions relationnelles.',
    comm_rule1_title: 'Spécifique',
    comm_rule1_desc: 'Nommez un comportement précis plutôt qu\'une généralité blessante.',
    comm_rule1_example: '« Quand tu ne m\'envoies pas de message après une soirée… » au lieu de « Tu te fiches de moi ».',
    comm_rule2_title: 'Non culpabilisant',
    comm_rule2_desc: 'Exprimez votre ressenti sans attaquer, juger ou blâmer l\'autre.',
    comm_rule2_example: '« Je me sens seul·e » plutôt que « Tu me rends seul·e ».',
    comm_rule3_title: 'Assertif',
    comm_rule3_desc: 'Assumez la légitimité de vos besoins — surtout si vous avez un profil anxieux qui craint d\'être « trop ».',
    comm_rule3_example: '« J\'ai besoin de réassurance, c\'est un besoin valide » non pas une faiblesse.',
    work_section_badge:  'Coaching professionnel',
    work_section_title:  'L\'attachement au travail aussi',
    work_section_desc:   'Les styles d\'attachement influencent notre rapport au travail, notre leadership et la sécurité psychologique en équipe.',
    work_section_cta:    'Explorer le coaching en entreprise',
    work_secure_label:   'Leader sécure :',
    work_secure_desc:    'inspire confiance, sait déléguer, crée un environnement de sécurité psychologique.',
    work_anxious_label:  'Collaborateur anxieux :',
    work_anxious_desc:   'cherche la validation de sa hiérarchie, risque le burn-out par épuisement.',
    work_avoidant_label: 'Collaborateur évitant :',
    work_avoidant_desc:  'privilégie l\'autonomie au détriment du travail d\'équipe et de la collaboration.',
    steps_badge:         'La méthode',
    steps_title:         'Vos 3 actions',
    step1_title:         'Faites le test',
    step1_desc:          '16 questions · 3 à 5 minutes · Résultat immédiat',
    step2_title:         'Session découverte',
    step2_desc:          'Séance offerte de 45 min pour découvrir vos 3 actions',
    step3_title:         'Passez à l\'action',
    step3_desc:          'Un plan clair et des outils pour des relations épanouissantes',
    multiculture_badge:   'Application professionnelle',
    multiculture_title:   'L\'attachement au travail — et dans les équipes multiculturelles',
    multiculture_subtitle: 'Les styles d\'attachement ne s\'arrêtent pas à la porte du bureau. Ils façonnent votre rapport au management, à l\'autorité, au feedback, et à la collaboration.',
    multiculture_entreprise_title: 'En entreprise : leadership et style d\'attachement',
    multiculture_entreprise_desc:  'Les styles d\'attachement influencent notre rapport au travail, notre leadership et la sécurité psychologique en équipe.',
    multiculture_mc_title: 'En équipe multiculturelle : l\'attachement amplifié',
    multiculture_mc_desc:  'Dans un environnement international, les styles d\'attachement se heurtent aux cultures de communication — directe vs indirecte, individuelle vs collective, explicite vs implicite. Monica, forte de 10 ans d\'expérience dans des équipes européennes et internationales, accompagne ces frictions avec une approche qui combine théorie de l\'attachement et intelligence interculturelle.',
    multiculture_note:      'Monica accompagne les marketers et professionnels internationaux qui jonglent entre cultures, organisations matricielles et transitions de poste — là où les styles d\'attachement sont les plus visibles.',
    multiculture_cta:       'Prendre rendez-vous →',
    booking_badge:       'Agenda',
    booking_title:       'Choisissez votre créneau',
    booking_subtitle:    'Séance découverte offerte · 45 minutes · Sans engagement',
    booking_cta_button:  'Voir les créneaux disponibles →',
    theory_badge:        'Références',
    theory_title:        'Les fondements théoriques',
    theory_subtitle:     'Cliquez sur une carte pour explorer les théories qui guident l\'approche de Monica.',
    theory_card_1_title: '📖 ATTACHED',
    theory_card_1_text:  'Comprendre son style d\'attachement',
    theory_card_2_title: '🌿 Carl Rogers',
    theory_card_2_text:  'L\'écoute inconditionnelle',
    theory_card_3_title: '❤️ Erich Fromm',
    theory_card_3_text:  'L\'art d\'aimer',
    theory_modal_cta:    'Réserver une séance découverte de 45 min →',
    footer_site_name:    'Happy Humans',
    footer_copyright:    '© Happy Humans — Monica Schneider',
    result_cta_title:    'Passez à l\'étape suivante',
    result_cta_subtitle: 'Séance découverte offerte de 45 minutes avec Monica',
    result_cta_button:   'Réserver ma séance découverte gratuite →',
    relations_price:     'Sur devis',
  },
  contact: {
    page_title:        'Parlons de ce qui vous amène.',
    intro_text:        "Que vous soyez en plein questionnement, en transition ou simplement curieux·se de voir si le dialogue peut aider — je vous invite à me contacter.",
    form_name_label:   'Votre nom',
    form_email_label:  'Votre email',
    form_subject_label:'Sujet (optionnel)',
    form_message_label:'Votre message',
    form_submit_label: 'Envoyer →',
    success_title:     'Message envoyé !',
    success_text:      'Monica vous répondra sous 48h.',
    sidebar_name:      'Monica Schneider',
    sidebar_title:     'Executive Coach · Philo-coaching',
  },
  navigation: {
    label_apropos:     'Monica',
    label_coaching:    'Coaching',
    label_entreprises: 'Entreprises',
    label_relations:   'Relations',
    label_temoignages: 'Témoignages',
    label_contact:     'Contact',
    label_cta:         'Réserver une séance',
  },
  'happiness-design': {
    // Hero
    hero_badge:    'Programme',
    page_title:    'Happiness Design',
    page_subtitle: '12 séances pour reprendre les rênes de votre vie et de votre bonheur — au boulot et ailleurs.',
    intro_text:    "Neurosciences, psychologie positive, philosophie pratique, design thinking — toutes les disciplines au service d'une transformation durable, pour que vous repreniez pleinement les rênes de votre vie.",
    hero_cta:      'Séance découverte gratuite (1h)',
    // Pour qui
    pourqui_badge:   'Pour qui',
    pourqui_title:   'Ce programme est fait pour vous si…',
    pourqui_1_title: 'Vous traversez une transition',
    pourqui_1_desc:  "Prise de poste, reconversion, promotion, départ, retraite, parentalité, séparation. Un nouveau chapitre s'ouvre — vous voulez l'aborder avec clarté.",
    pourqui_2_title: 'Vous avez perdu le fil',
    pourqui_2_desc:  "Le boulot tourne, mais quelque chose sonne creux. Vous fonctionnez, mais vous n'habitez plus vraiment votre vie.",
    pourqui_3_title: 'Vous voulez reprendre les rênes',
    pourqui_3_desc:  "Pas juste 'aller mieux' — reprendre activement en main votre bonheur, vos relations, votre impact. Avec des outils concrets, pas du développement personnel vague.",
    // Programme
    program_badge: 'Le programme',
    program_title: '12 séances + 4 follow-ups',
    // 12 étapes
    step_01_title: 'Comment ça marche',       step_01_desc: 'Neurosciences + gratitude',
    step_02_title: 'Audit de sa vie',         step_02_desc: 'Life Design / Bonheur',
    step_03_title: 'Audit du boulot',         step_03_desc: 'Design Thinking appliqué à votre vie professionnelle',
    step_04_title: 'Audit des forces',        step_04_desc: 'Identifier vos ressources et atouts profonds',
    step_05_title: 'Forces pratiquées',       step_05_desc: "Via Character Strengths — lesquelles activez-vous vraiment ?",
    step_06_title: "L'échec",                 step_06_desc: "Changer son rapport à l'échec — audit des freins",
    step_07_title: 'Audit des freins',        step_07_desc: "Syndrome de l'imposteur · Attachement (TA) · Peurs (fears)",
    step_08_title: 'Homo risibilis',          step_08_desc: "Imparfait mais impactant — l'action salvatrice",
    step_09_title: 'V1 / V2',                step_09_desc: 'Qui je suis, qui je veux devenir',
    step_10_title: 'Les 3 métamorphoses',     step_10_desc: 'Les trois transformations clés de votre parcours',
    step_11_title: "Child's Plan",            step_11_desc: 'Jalons avec rappels pour ancrer les engagements',
    step_12_title: 'Follow-ups × 4',         step_12_desc: '4 sessions de suivi pour consolider et ancrer le changement',
    // Boîte à outils
    tools_badge:             'Programme',
    tools_title:             'Une boîte à outils multidisciplinaire',
    tools_intro_1:           "Ce n'est pas le bonheur qui fait la différence, mais comment on réagit dans l'adversité. Et une seule discipline ne suffit pas.",
    tools_intro_2:           "Happiness Design mêle neurosciences, psychologie positive, psychologie classique, méditation, pratique philosophique et design thinking — pour coller au plus près de votre chemin unique.",
    tools_origin_label:      "L'origine",
    tools_origin_text:       "Cette méthode est née d'un mémoire de Master de Pratique Philosophique sur le bonheur, et de 6 ans d'expérimentation personnelle par Monica Schneider.",
    tools_conclusions_label: 'Deux conclusions fondatrices :',
    tools_conclusion_1:      "Ce n'est pas le bonheur qui fait la différence, c'est comment on réagit dans l'adversité.",
    tools_conclusion_2:      "Une seule discipline ne suffit pas. Il faut comprendre son cerveau, savoir créer son bonheur, repérer quand l'inconscient reprend le dessus, entraîner son cerveau à réduire le cortisol et challenger ses pensées.",
    tools_claim:             "Happy Humans est la seule pratique de coaching en France qui intègre ces 6 disciplines dans un programme cohérent.",
    // Tarifs
    pricing_badge:           'Investissement',
    pricing_title:           'Un programme sur mesure',
    format_label:            'Format',
    format_value:            '12 séances + 4 follow-ups',
    duration_label:          'Durée',
    duration_value:          '60 min',
    rhythm_label:            'Rythme',
    rhythm_value:            '1 séance / 2 semaines',
    price_label:             'Tarif',
    price_value:             'Sur devis',
    cta_label:               'Demander un devis →',
    program_complete_features: "12 séances d'1h en individuel\n4 sessions de suivi post-programme\nOutils et exercices entre les séances\nEn ligne ou en présentiel (Paris)",
    program_complete_cta:    'Réserver une séance découverte →',
    // Découverte
    discovery_label:     'Séance découverte',
    discovery_price:     'Offerte',
    discovery_unit:      '1h · Sans engagement',
    discovery_features:  "Échange sur votre situation\nPrésentation du programme\nQuestions / réponses\nDécision libre à l'issue",
    discovery_cta:       'Réserver maintenant →',
    // CTA
    cta_title:    "Prêt·e à reprendre les rênes ?",
    cta_subtitle: "Commençons par une séance découverte d'1h — gratuite et sans engagement.",
    cta_button:   'Réserver ma séance découverte →',
  },
  temoignages: {
    hero_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1400&q=80&auto=format&fit=crop',
    page_title: 'Ils témoignent',
    intro_text: 'Des parcours différents, une même expérience : retrouver de la clarté et avancer avec confiance.',
    grid_badge:      'Témoignages',
    grid_empty_state: 'Les témoignages arrivent bientôt.',
    linkedin_badge:       'Témoignages LinkedIn',
    linkedin_title:       "Ce qu'ils écrivent en public",
    linkedin_subtitle:    'Verbatim issus des recommandations LinkedIn — en version originale.',
    linkedin_footnote:    '* Prénom modifié · Témoignages publiés avec accord',
    linkedin_intro_note:  '',
    cta_title:     "Prêt·e à écrire votre propre histoire ?",
    cta_subtitle:  'Réservez une séance découverte gratuite de 30 minutes.',
    cta_coaching: 'Découvrir le coaching',
    cta_contact:  'Prendre contact',
  },
  footer: {
    site_name:     'Happy Humans',
    tagline:       'philo-coaching',
    description:   'Coaching & transformation avec Monica Schneider.',
    description_2: 'Une pratique qui relie leadership, authenticité, philosophie et transformation humaine.',
    linkedin_url:  'https://fr.linkedin.com/in/monica-schneider-philo-coaching',
    service_1:     'Executive coaching individuel',
    service_2:     'Coaching de dirigeants',
    service_3:     'Philosophical counselling',
    service_4:     'Sparring partner',
    service_5:     'Ateliers et séminaires',
    copyright:     'Happy Humans — Monica Schneider. Tous droits réservés.',
    footer_nav_show_temoignages: 'false',
  },
};
