// Valeurs par défaut de chaque page — miroir des DEFAULTS dans chaque composant
// Utilisé par le CMS admin pour pré-remplir les champs vides
export const PAGE_DEFAULTS: Record<string, Record<string, string>> = {
  home: {
    hero_badge:           'Monica Schneider · Executive Coach · Happy Humans',
    hero_title:           "Clarté, confiance et relations qui vous ressemblent",
    hero_subtitle:        "Executive Coach certifiée AoEC · EMCC Practitioner · Philosophical Counselling",
    hero_cta_primary:     "Découvrir l'approche →",
    hero_cta_secondary:   'Séance découverte gratuite',
    services_title:       'Comment puis-je vous aider ?',
    services_b2c_title:   'Pour les individus',
    services_b2c_text:    "Managers, dirigeants, entrepreneurs ou personnes en transition qui veulent retrouver de la clarté, de la confiance et une direction qui leur ressemble vraiment.",
    services_b2c_cta:     'Réserver une séance découverte →',
    services_b2b_title:   'Pour les organisations',
    services_b2b_text:    "Coaching de leadership, ateliers, séminaires et accompagnement du changement pour remettre de l'alignement et de l'élan dans les équipes.",
    services_b2b_cta:     "Discuter d'un projet →",
    test_title:           "Quel est votre style d'attachement ?",
    test_subtitle:        "Découvrez si vous êtes sécure, anxieux ou évitant — et ce que cela change dans vos relations. 16 questions · 5 minutes · Résultat immédiat.",
    test_cta:             'Faire le test gratuit',
    booking_title:        'Prenez rendez-vous',
    booking_subtitle:     'Séance découverte offerte · 45 minutes · Sans engagement',
    contact_title:        'Une question ? Écrivez-nous',
    contact_intro:        'Je réponds personnellement à chaque message sous 48h. — Monica',
    contact_email:        'happyhumans.coaching@gmail.com',
  },
  'a-propos': {
    page_title:    'Monica Schneider — leadership, coaching et profondeur',
    intro_text:    "Une pratique née au croisement de l'entreprise, du branding, de la transformation humaine et du philosophical counselling.",
    bio_title:     'Une trajectoire entre direction, marque et accompagnement.',
    bio_text:      "10+ ans de leadership en marketing et transformation. Executive Coach certifiée AoEC et EMCC Practitioner. Master en Philosophical Counselling and Consultancy. Accompagnement en français, anglais et roumain.",
    valeurs_title: 'Ce qui oriente la pratique',
    valeurs_text:  "Authenticité, rigueur intellectuelle, présence et transformation durable.",
  },
  coaching: {
    hero_title:         "Il y a des moments où il faut réapprendre à habiter son rôle.",
    hero_subtitle:      "Executive Coach certifiée AoEC · EMCC Practitioner · Philosophical Counselling — Monica Schneider accompagne des managers, dirigeants et personnes en transition.",
    coaching_b2c_title: 'Coaching individuel',
    coaching_b2c_text:  "Un espace pour ralentir, regarder ce qui se passe vraiment — et construire un mouvement qui tient dans la durée.\n\nLe coaching que je propose n'est pas un conseil. C'est un accompagnement qui part de là où vous êtes vraiment.",
    coaching_b2b_title: 'Pour les organisations',
    coaching_b2b_text:  "Coaching de dirigeants, ateliers de cohésion, accompagnement du changement et séminaires sur mesure.\n\nQuand une équipe perd de sa cohérence, les résultats s'en ressentiront toujours.",
    form_intro:         'Décrivez votre enjeu ou posez une question — je vous répondrai sous 48h.',
    reassurance:        '100% confidentiel · Sans engagement · Réponse sous 48h · Séance découverte offerte',
  },
  entreprises: {
    page_title:    "Remettre de l'alignement et de l'élan dans vos équipes.",
    intro_text:    "Happy Humans accompagne les organisations avec une approche qui combine coaching de leadership, philosophical counselling et design d'expériences collectives.",
    section_title: 'Ce que nous proposons',
    section_text:  "Coaching de dirigeants et managers · Ateliers de cohésion · Accompagnement du changement · Séminaires sur mesure",
  },
  relations: {
    hero_badge:          'Relations & Attachement · Happy Humans',
    hero_title:          "Quel est votre style d'attachement ?",
    hero_description:    'Un outil de découverte douce pour mieux comprendre comment vous vous connectez aux autres.',
    quiz_pill_1:         '⏱ 3 à 5 minutes',
    quiz_pill_2:         '📝 16 questions',
    quiz_pill_3:         '✨ Résultats immédiats',
    quiz_cta:            'Commencer le test →',
    result_cta_title:    'Passez à l\'étape suivante',
    result_cta_subtitle: 'Séance découverte offerte de 45 minutes avec Monica',
    result_cta_button:   'Réserver ma séance découverte gratuite →',
    booking_title:       'Choisissez votre créneau',
    booking_subtitle:    'Séance découverte offerte · 45 minutes · Sans engagement',
    theory_title:        'Les fondements théoriques',
    theory_card_1_title: '📖 ATTACHED',
    theory_card_1_text:  "Comprendre son style d'attachement",
    theory_card_2_title: '🌿 Carl Rogers',
    theory_card_2_text:  "L'écoute inconditionnelle",
    theory_card_3_title: '❤️ Erich Fromm',
    theory_card_3_text:  "L'art d'aimer",
  },
  contact: {
    page_title:        'Parlons de ce qui vous amène.',
    intro_text:        "Que vous soyez en plein questionnement, en transition ou simplement curieux·se de voir si le dialogue peut aider — je vous invite à me contacter.",
    form_name_label:   'Votre nom',
    form_email_label:  'Votre email',
    form_subject_label:'Sujet (optionnel)',
    form_message_label:'Votre message',
    form_submit_label: 'Envoyer →',
    success_title:     'Message envoyé !',
    success_text:      'Monica vous répondra sous 48h.',
    sidebar_name:      'Monica Schneider',
    sidebar_title:     'Executive Coach · Philo-coaching',
  },
  navigation: {
    label_apropos:     'Monica',
    label_coaching:    'Coaching',
    label_entreprises: 'Entreprises',
    label_relations:   'Relations',
    label_temoignages: 'Témoignages',
    label_contact:     'Contact',
    label_cta:         'Réserver une séance',
  },
  'happiness-design': {
    page_title:    'Happiness Design',
    page_subtitle: '12 séances pour reprendre les rênes de votre vie et de votre bonheur — au boulot et ailleurs.',
    intro_text:    "Neurosciences, psychologie positive, philosophie pratique, design thinking — toutes les disciplines au service d'une transformation durable et profonde.",
  },
  temoignages: {
    hero_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1400&q=80&auto=format&fit=crop',
    page_title: 'Ils témoignent',
    intro_text: 'Des parcours différents, une même expérience : retrouver de la clarté et avancer avec confiance.',
  },
  footer: {
    site_name:     'Happy Humans',
    tagline:       'philo-coaching',
    description:   'Coaching & transformation avec Monica Schneider.',
    description_2: 'Une pratique qui relie leadership, authenticité, philosophie et transformation humaine.',
    linkedin_url:  'https://fr.linkedin.com/in/monica-schneider-philo-coaching',
    service_1:     'Executive coaching individuel',
    service_2:     'Coaching de dirigeants',
    service_3:     'Philosophical counselling',
    service_4:     'Sparring partner',
    service_5:     'Ateliers et séminaires',
    copyright:     'Happy Humans — Monica Schneider. Tous droits réservés.',
  },
};
